name: Benchmark

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  bench:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    steps:
      - uses: actions/checkout@v6

      - name: Restore cached benchmark results
        id: cache-results-restore
        uses: actions/cache/restore@v5
        with:
          path: results
          key: ${{ runner.os }}-results

      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 11
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Bench
        run: pnpm bench

      - name: Remove old cached benchmark results
        if: github.event_name == 'push'
        env:
          GH_TOKEN: ${{ github.token }}
          CACHE_KEY: ${{ steps.cache-results-restore.outputs.cache-primary-key }}
        run: |
          gh cache list -k "$CACHE_KEY" --json id --jq '.[0].id'
          CACHE_ID=$(gh cache list -k "$CACHE_KEY" --json id --jq '.[0].id')
          [ -n "$CACHE_ID" ] && gh cache delete "$CACHE_ID"

      - name: Save cached benchmark results
        if: github.event_name == 'push'
        id: cache-results-save
        uses: actions/cache/save@v5
        with:
          path: results
          key: ${{ steps.cache-results-restore.outputs.cache-primary-key }}
